version: '3.1'
services:
  ssh-honeypot:
    image: wildwildangel/ssh-honeypotd
    restart: always
    network_mode: host
    cap_add:
      - net_admin
    ports:
      - 21:21
    environment:
      - TZ=Europe/Berlin
      - ADRESS=0.0.0.0
      - PORT=21
    container_name: ssh-honeypot
