version: '3.1'
services:
  gmod_ttt:
    container_name: "gmod_ttt"
    image: joshhsoj1902/linuxgsm-docker
    environment:
      - LGSM_GAMESERVERNAME=gmodserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE
      - LGSM_DEFAULTMAP=ttt_rooftops_2016_v1
      - LGSM_GAMEMODE=terrortown
      - LSGM_WSAPIKEY=...
      - LGSM_WSCOLLECTIONID=843519054
      - LGSM_MAXPLAYERS=32
    ports:
      - 27015:27015
      - 27005:27005
      - 27005:27005
    volumes:
      - ./:/home/linuxgsm/serverfiles
